"""Deny classification, done when the gateway decides (moved from the consume-plane gateway-violations plugin).

Families group the reason codes the gateway and policy engine actually emit, so the trace and
dashboard can count interventions by kind without a Layer 3 pass.
"""

_FAMILIES = {
    "SCOPE": ("CASE_OUT_OF_SCOPE", "RESOURCE_OUT_OF_SCOPE", "DOCUMENT_OUT_OF_SCOPE", "REGISTRY_OUT_OF_SCOPE",
              "SCREEN_SUBJECT_OUT_OF_SCOPE", "TOOL_DENIED", "ACTION_KIND_DENIED", "TRANSPORT_DENIED", "TASK_SCOPE",
              "INVALID_TOOL_ARGUMENTS", "INVALID_CREATE_FIELDS"),
    "PREREQUISITE": ("APPLICATION_NOT_READ", "DOCUMENTS_NOT_READ", "DOCUMENTS_NOT_EXTRACTED", "REGISTRY_NOT_READ",
                     "SCREENING_NOT_COMPLETE", "SCREENING_HIT_REQUIRES_ESCALATION", "RISK_NOT_COMPUTED",
                     "RISK_NOT_VERIFIED", "HIGH_RISK_CREATE_DENIED", "IDENTITY_DOCUMENT_EXPIRED",
                     "APPLICATION_ALREADY_DECIDED", "CLIENT_ALREADY_EXISTS", "SCREENING_SOURCE_CHANGED",
                     "INVALID_RISK_FACTORS", "RISK_FACTORS_MISMATCH"),
    "IDENTITY": ("IDENTITY_CONFLICT", "IDENTITY_ARGUMENT_FORBIDDEN", "APPROVED_IDENTITY_MISMATCH",
                 "APPROVED_IDENTITY_REDACTION", "SIDE_EFFECT_MISMATCH", "UNKNOWN_RUN", "REPLAY",
                 "EFFECT_REPLAY_MISMATCH"),
    "EGRESS": ("DOMAIN_BLOCKLISTED", "EGRESS_NOT_ALLOWLISTED", "RECIPIENT_NOT_ALLOWLISTED"),
    "SUPPLY_CHAIN": ("MODEL_SOURCE_DENIED", "MODEL_SIGNATURE_DENIED"),
    "CONTENT": ("SIGNATURE_MATCH", "PRIVACY_MATCH", "SIGNATURE_IN_KEY", "OUTPUT_INSPECTION_BLOCK", "AUDITOR_BLOCK",
                "AUDITOR_UNAVAILABLE"),
    "BUDGET": ("BUDGET_EXHAUSTED", "ADMISSION_CAPACITY"),
    "APPROVAL": ("APPROVAL_REQUIRED", "APPROVAL_NOT_IMPLEMENTED"),
    "CONTROL": ("SESSION_HALTED", "SESSION_FINISHED", "INTERVENTION_BLOCKED_TOOL", "INVALID_ARGUMENTS"),
}
REASON_FAMILIES = {code: family for family, codes in _FAMILIES.items() for code in codes}


def classify(code: str | None) -> str:
    return REASON_FAMILIES.get(code or "", "UNCLASSIFIED")
